version: "3"
services:
  queue:
    image: tarantool/tarantool:latest
    command: tarantool /code/queue.lua
    stdin_open: true
    tty: true
    ports:
      - 3301:3301
    volumes:
      - ./:/code
